[project]
requires-python = ">=3.6"

[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.ini
  |\.c
  |\.cpp
  |\.hpp
  |\.h
  |\.txt
  |Dockerfile
  |Jenkinfile
)/
'''
