name: Deploy Wheels

on:
  push:
    tags:
      - v*.*.*

jobs:
  branch_check:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.ref.outputs.result }}
      master: ${{ steps.master.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - id: ref
        name: ref branch check
        run: echo "::set-output name=result::$(git log -1 --format='%H')"
      - uses: actions/checkout@v3
        with:
          ref: master

      - id: master
        name: master branch check
        run: echo "::set-output name=result::$(git log -1 --format='%H')"
          

  deploy_wheels:
    needs: branch_check
    name: Deploy wheels
    runs-on: ubuntu-20.04
    if: needs.branch_check.outputs.tag == needs.branch_check.outputs.master

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Install deps
        run: pip install build twine

      - name: Build Wheels
        run: python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Get Changelog
        id: vars
        run: | 
          lineNo=$(grep -n "## v" CHANGELOG.md | awk '{split($0,a,":"); print a[1]}' | tail -n 1)
          lineNo=$((lineNo+1))
          contents=$(tail -n +$lineNo CHANGELOG.md)
          echo "::set-output name=change::$contents"

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          draft: false
          prerelease: false
          body: ${{ steps.vars.outputs.change }}
