name: Build Wheels

on:
  push:
    branches:    
      - main
    tags:
      - v*.*.*
  workflow_run:
    workflows:
      - "Build & Test"
    branches: [main]
    types: [completed]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install deps
        run: pip install build twine

      - name: Build Wheels
        run: python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Get Changelog
        id: vars
        run: | 
              lineNo=`grep -n "## v1.0.1" CHANGELOG.md | awk '{split($0,a,":"); print a[1]}'`
              lineNo=$((lineNo+1))
              contents=`tail -n +$lineNo CHANGELOG.md`
              echo ::set-output name=change::${ contents }

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          draft: false
          prerelease: false
          body: ${{ steps.vars.outputs.change }}
